### ISSUE TITLE
Como retornar mais de 100 records?

### ISSUE THREAD

**Issue by danielhrc** [xavierlaerte/labex-20.1#1]
fiz a query:
{
  search(query: "stars:>100", type: REPOSITORY, first: 1000) {
    nodes {
      ... on Repository {
        nameWithOwner
        diskUsage
      }
    }
  }
}

E obtive um erro de EXCESSIVE PAGINATION - com a mensagem  "Requesting 1000 records on the `search` connection exceeds the `first` limit of 100 records.". 
A minha dúvida é a seguinte:
**Como que faz para retornar uma consulta com mais de 100 records?**

**Comment by xavierlaerte** [comment]
Oi Daniel,

Como falei na última aula, o limite de resposta da API é de 100 itens por páginas. Por isso, começamos criando um script para as 100 primeiras respostas. Em seguida, faremos paginação nas 9 próximas páginas de resposta (para coletar os 1.000 repositórios).

Caso queira adiantar, segue exemplo: https://graphql.org/learn/pagination/
