### ISSUE TITLE
Dificuldade no GQM LAB 3

### ISSUE THREAD

**Issue by Leusd** [xavierlaerte/labex-20.1#11]
Boa tarde, professor, 

Reunimos para discutir acerca do laboratório 3 cujo objetivo geral é ”Analisar, do ponto de vista do desenvolvedor, se issues do GitHub também são discutidas no Stackoverflow”. Estamos com dificuldades em determinar métricas, pois não sabemos se compreendemos bem o que foi solicitado, já que tudo que pensamos envolveriam aplicações de algoritmos complexos para manejo de texto. 

Assistimos à aula passada novamente no Microsoft Teams, porém a dúvida persistiu. Procuramos o enunciado para maiores informações e não encontramos. Além disso, conversamos com outros alunos e eles também demonstraram dificuldades no mesmo sentido. Sendo assim, poderia nos auxiliar com essa dúvida na próxima aula, por favor?

No aguardo de seus comentários. 
Agradeço de imediato. 

João, Maria Verônica e Talita

**Comment by xavierlaerte** [comment]
Oi pessoal,

Respondi para todos ontem, via SGA. Muitos tiveram problemas parecidos. Vamos discutir hoje a noite.

Obrigado pelo feedback!
