### ISSUE TITLE
Problema de autenticação

### ISSUE THREAD

**Issue by DanielVargas13** [xavierlaerte/labex-20.1#3]
Caro Laerte,

Eu consegui fazer o script para obter os dados necessários de 100 repositórios, porém estou tendo um problema onde o GitHub está apagando meu token de acesso toda vez que eu commito alguma alteração no script. Isso ocorre devido ao fato do GitHub detectar o token no commit e apagá-lo por questões de segurança. Peço ao senhor que utilize o token anexado nesse issue para testar o script.

[token.txt](https://github.com/xavierlaerte/labex-20.1/files/4231716/token.txt)

Desde já agradeço,
Daniel

**Comment by xavierlaerte** [comment]
Oi Daniel (e demais),

De fato, o Github não permite a publicação do seu token (ainda bem)! Aproveito para avisar que o commit pode ser com a chave de token vazia no script. Vou fazer uma análise manual nessa primeira entrega.
