### ISSUE TITLE
Artigos para TIS VI

### ISSUE THREAD

**Issue by talitaam** [xavierlaerte/labex-20.1#5]
Oi Professor! Falei que iria abrir uma issue para lembra de responder o email da Maria Verônica... O remetente é veronicasoares4@gmail.com e o assunto é Sugestão de artigos para TIS VI.
Obrigada!!

**Comment by xavierlaerte** [comment]
Respondido! :-)

**Comment by talitaam** [comment]
Obrigada!!!
